; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.39"

; Modules - Custom
projects[nci_SSO][type] = "module"
projects[nci_SSO][subdir] = "custom"
projects[nci_SSO][download][type] = "svn"
projects[nci_SSO][download][url] = "https://OLD_SVN/svn/oce_dev/Products/Drupal/shared/modules/Custom/nci_SSO/branches/1.3"
projects[nci_SSO][download][interactive] = "true"

; Modules - Development-only
projects[features][subdir] = "dev"
projects[features][version] = "2.7"

projects[features_extra][subdir] = "dev"
projects[features_extra][version] = "1.0"

; Modules - Contributed
projects[autologout][subdir] = "contrib"
projects[autologout][version] = "4.4"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.9"

projects[captcha][subdir] = "contrib"
projects[captcha][version] = "1.3"

projects[config_perms][subdir] = "contrib"
projects[config_perms][version] = "2.1"

projects[date][subdir] = "contrib"
projects[date][version] = "2.9"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.6"

projects[field_collection][subdir] = "contrib"
projects[field_collection][version] = "1.0-beta8"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.5"

projects[panels_everywhere][subdir] = "contrib"
projects[panels_everywhere][version] = "1.0-rc2"

projects[imce][subdir] = "contrib"
projects[imce][version] = "1.9"

projects[imce_wysiwyg][subdir] = "contrib"
projects[imce_wysiwyg][version] = "1.0"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "3.0-alpha2"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"

projects[link][subdir] = "contrib"
projects[link][version] = "1.3"

projects[nodequeue][subdir] = "contrib"
projects[nodequeue][version] = "2.0"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.3"

projects[recaptcha][subdir] = "contrib"
projects[recaptcha][version] = "2.0"

projects[role_delegation][subdir] = "contrib"
projects[role_delegation][version] = "1.1"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[token][subdir] = "contrib"
projects[token][version] = "1.6"

projects[url][subdir] = "contrib"
projects[url][version] = "1.0"

projects[views][subdir] = "contrib"
projects[views][version] = "3.11"

projects[workbench][subdir] = "contrib"
projects[workbench][version] = "1.2"

projects[workbench_moderation][subdir] = "contrib"
projects[workbench_moderation][version] = "1.4"

projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.2"

projects[wysiwyg_filter][subdir] = "contrib"
projects[wysiwyg_filter][version] = "1.6-rc2"

; Themes
projects[zurb_foundation][version] = "5.0-rc6"
