<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
* Subscribe to the listserv by sending an email with the subscription parameters in the body. Subscription requests contain email only, no name.
* @param $email_address: email address to be added to the listserv
*/
function _ttc_blocks_listserv_subscribe($email_address) {
    $success = 'Request submitted. Please check your email and follow the directions contained therein to confirm your subscription.';
	$failure = 'Please enter a valid email address.';
 
    /* ListServ subsribe and validation happens here */
    $error = 0;

    //Test for empty email
    if ($email_address == '' || $email_address === null) {
        $error = 1;
    }

    //Test for valid email
    if (!filter_var($email_address, FILTER_VALIDATE_EMAIL)) {
        $error = 2;
		$failure = 'Please enter a valid email address.';
    }

    //Try and send email. If successful, display success message and return.
    if ($error == 0) {
        if (mail("FAKEEMAIL@FAKEEMAIL.FAKEEMAIL", "Listserv Subscription", "SUB OCPL-APPDEV-DEV Anonymous", "From: " . $email_address)) {
            return $success;
        } else {
            $error = 3;
			$failure = 'Listserv subscription failed. Please try again.';
        }
    }

    //If we are here, there was an error. Display error message 
	//drupal_goto('/', array('query' => array('err' => $error))); //Add error code query - commenting out for now
    return $failure;
}