<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
* Render the HTML for the listserv subscription form
*/
function _ttc_blocks_listserv_subscribe_block() {
	$subscribe_block = '
	  <form class="listserv-subscribe-block" action="" id="" accept-charset="UTF-8">
		<div class="container-inline">
		  <h4 class="field-content">SUBSCRIBE</h4>
		  <div class="">Subscribe to our Available Technology Listserv to receive the latest announcements</div>
		  <div class="row">
			<div class="small-8 columns listserv-input-container">
			  <div class="form-item form-type-textfield">
				<input type="text" title="Enter an email address to subscribe." placeholder="Your Email Address..." class="subscribe-form-input-text" id="subscribe-block-form-0" name="ls" value="" size="15" maxlength="128" />
			  </div>
			</div>
			<div class="small-4 columns listserv-submit-container">
			  <button class="button radius postfix expand primary form-submit" id="edit-submit" name="op" value="Subscribe" type="submit">Subscribe</button>
			</div>
		  </div>
		</div>
	  </form>';
    return $subscribe_block;
}

/**
* Subscribe to the listserv by sending an email with the subscription parameters in the body. Subscription requests contain email only, no name.
* @param $email_address: email address to be added to the listserv
*/
function _ttc_blocks_listserv_subscribe($email_address) {
    $success = 'Request submitted. Please check your email and follow the directions contained therein to confirm your subscription.';
	$failure = 'Please enter a valid email address.';
 
    /* ListServ subsribe and validation happens here */
    $error = 0;

    //Test for empty email
    if ($email_address == '' || $email_address === null) {
        $error = 1;
    }

    //Test for valid email
    if (!filter_var($email_address, FILTER_VALIDATE_EMAIL)) {
        $error = 2;
		$failure = 'Please enter a valid email address.';
    }

    //Try and send email. If successful, display success message and return.
    if ($error == 0) {
        if (mail("FAKEEMAIL@FAKEEMAIL.FAKEEMAIL", "Listserv Subscription", "SUB OCPL-APPDEV-DEV Anonymous", "From: " . $email_address)) {
            return $success;
        } else {
            $error = 3;
			$failure = 'Listserv subscription failed. Please try again.';
        }
    }

    //If we are here, there was an error. Display error message 
	//drupal_goto('/', array('query' => array('err' => $error))); //Add error code query - commenting out for now
    return $failure;
}