<?php

/**
 * @file
 * Code for the TTC Search feature.
 */
include_once 'ttc_search.features.inc';

/**
 * Used to inform the CTools plugin system about the location of a directory 
 * that should be searched for files containing plugins of a particular type.
 * @see hook_ctools_plugin_directory($owner, $plugin_type)
 * 
 * @link http://drupalcontrib.org/api/drupal/contributions!ctools!ctools.api.php/function/hook_ctools_plugin_directory/7
 * 
 * @param type $module The system name of the module owning the plugin type for 
 *      which a base directory location is being requested.
 * @param type $plugin The name of the plugin type for which a base directory 
 *      is being requested.
 * @return string The path where CTools' plugin system should search for plugin 
 *      files, relative to your module's root. Omit leading and trailing slashes.
 */
function ttc_search_ctools_plugin_directory($module, $plugin) {
    if ($module == 'ctools' && !empty($plugin)) {
        return "plugins/$plugin";
    }
}
